# Generated by Django 5.1.3 on 2024-11-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_staff_user_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
