# Generated by Django 5.1.3 on 2024-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_baseuser_is_student_alter_baseuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Maths', 'Maths'), ('Politics', 'Politics'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Botany', 'Botany'), ('Zoology', 'Zoology')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
