# Generated by Django 5.1.3 on 2024-11-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_staff_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff User', 'verbose_name_plural': 'Staff Users'},
        ),
    ]
