# Generated by Django 5.1.3 on 2024-11-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_baseuser_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Maths', 'Maths'), ('Politics', 'Politics'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Botany', 'Botany'), ('Zoology', 'Zoology')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='students', to='Authentication.subject_info'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_subject', to='Authentication.subject_info'),
        ),
    ]
