# Generated by Django 5.1.3 on 2024-11-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_subject_info_alter_baseuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_subject', to='Authentication.subject_info'),
        ),
    ]
